### ISSUE TITLE
Mind maps

### ISSUE THREAD

**Issue by phylophyl** [freedombox/freedombox.org#1]
![landing-page-mind-img-format](https://cloud.githubusercontent.com/assets/15269304/11926361/7269295c-a7c4-11e5-8106-5224017d3339.png)

**Comment by phylophyl** [comment]
Landing page first mokup (thanks to sunil)

![initial_suggestion](https://cloud.githubusercontent.com/assets/15269304/11926399/d57d3902-a7c4-11e5-9868-aaac6a858d23.png)

**Comment by phylophyl** [comment]
additional infos (mjones on IRC):

"the goal is to communicate that the freedombox software project is making things for normal people, has something usable, and is an active project"

"a big purpose of this page should be to recruit new developers to help with the stuff you are mentioning"

**Comment by mray** [comment]
is this an issue in the sense of something that needs to be done to close it? If so - what needs to be done?
If note it could get closed.

**Comment by jvalleroy** [comment]
I think this can be closed. We may want to open other issues for specific TODOs. The mind map and info looks nice, but it may be better to put it on the wiki.
