### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedombox.org#13]
Should the site content also be under AGPL? Or should it be CC-BY-SA, like the wiki? (Maybe dual licensed?)

**Comment by mray** [comment]
I'd expect creative commons to be the best match to the website since it isn't about the code but the content that needs to be free. The CMS we use is free anyway.

**Comment by SunilMohanAdapa** [comment]
With the merge of #14 , license is now CC-BY-SA 4.0 International.
