### ISSUE TITLE
Mock-ups

### ISSUE THREAD

**Issue by phylophyl** [freedombox/freedombox.org#2]
Landing page first mokup (thanks to sunil)

![initial_suggestion](https://cloud.githubusercontent.com/assets/15269304/11926399/d57d3902-a7c4-11e5-9868-aaac6a858d23.png)

**Comment by phylophyl** [comment]
Fisrt shot for templates options:

1 - http://willianjusten.com.br/will-jekyll-template/ (to made a landing page with no posts)
2 - http://themes.3rdwavemedia.com/demo/devaid/
3 - a mix between http://jeromelachaud.github.io/freelancer-theme/ + http://jekyllthemes.org/themes/agency/ to build this mock up https://github.com/freedombox/freedombox.org/issues/2

IRC comment (thanks to Dietmar)
[1] is a very popular style these days, can it just make blogs? [2] is a very nice style, also very popular, and can be easily populated and direct the user. freelancer I find too "childish", too many pictures. So my favorite would be [2] in the colors of [1]

**Comment by phylophyl** [comment]
This architecture is not bad https://linuxacademy.com/certifications

**Comment by SunilMohanAdapa** [comment]
Item 2 looks best among them (although i'd prefer something with lot less color or borders).

**Comment by mray** [comment]
On 28.01.2016 12:59, Philippe Baret wrote:
> Fisrt shot for templates options:
> 
> 1 - http://willianjusten.com.br/will-jekyll-template/ (to made a landing page with no posts)
> 2 - http://themes.3rdwavemedia.com/demo/devaid/
> 3 - a mix between http://jeromelachaud.github.io/freelancer-theme/ + http://jekyllthemes.org/themes/agency/ to build this mock up https://github.com/freedombox/freedombox.org/issues/2
> 
> IRC comment (thanks to Dietmar)
> [1] is a very popular style these days, can it just make blogs? [2] is a very nice style, also very popular, and can be easily populated and direct the user. freelancer I find too "childish", too many pictures. So my favorite would be [2] in the colors of [1]
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/freedombox/freedombox.org/issues/2#issuecomment-176144848
> 

Hi there,

there is no need to go for ready made templates. I made a design based
on the outcome of the last meeting.
Ideally I'd like to discuss it on the visual mailing list.
Despite being able to post to it, it seems to be gone.

Anybody has info about the status of that list?


Cheers,
Robert

**Comment by phylophyl** [comment]
Hi Robert, nice, i have no idea about this visual mailing list though, possible to paste the image here?
Cheers,
Philippe

**Comment by mray** [comment]
It isn't 100% polished and contains place-holder text, but clearly is not just a mockup. 
The page introduces the project and presents use-cases in a fuzzy weighted manner with focus on the uppermost use-case.
It also links to the three main parts that are:

* get hardware
* download software
* setup for certain cases

![1](https://cloud.githubusercontent.com/assets/164785/12696303/6148d1d2-c767-11e5-9635-69b0cfa5ad27.png)

posting the other 7 screens here seems too much.

**Comment by phylophyl** [comment]
Nice :)

Here is some content made separatly, it can be used with an adpation i guess.

Top Menu: Features | About | Download

FREEDOMBOX
Personal server for Privacy

WHAT IS FREEDOMBOX?
Tired of giving all your life and your datas to Internet giants ? Install FreedomBox on a min-PC and take your privacy back home. This personal server is as easy to use as a smartphone and can handle emails, encrypted chats and calls, file sharing, ad blocking, VPN and much more. FreedomBox is also a wireless router that you can trust. 

FEATURES

VPN---------------------------------------Blog
Chat---------------------------------------IRC
Conference Calls-----------------------Torrent
Files---------------------------------------Tor Hidden Service
Emails Client-----------------------------Tor Bridges
Wiki----------------------------------------PageKite

USER EXPERIENCE

"As a journalist and non techy person, i can use encrypted chats and private vpn without decicating too much time on installations and 

"Thanks to the quality of its discussion list, my experience with FreedomBox as a potential platform has been superb."

"A single board computer (SBC) and FreedomBox seem like a good thing for power, I can keep on all the time."

"I need FreedomBox to be able to get others to work on the same privacy level, and it is not viable to ask them to do what i did, learn all that stuff and setup tools one by one. There is no freedom in isolation."

ABOUT 

FreedomBox free software is a project raised by Eben Moglen and Software Freedom Law Center. Is it a subset of the Debian universal operating system. As such, FreedomBox is composed entirely of free software.

HOW TO START USING IT

FreedomBox can be installed on open and cost-effectiv single board computers. Computers running Debian operating system (linux) and virtual machines are also supported. Here is the list of supported devices.

A20 OLinuXino Lime2 ---------------------------Cubietruck
A20 OLinuXino MICRO--------------------------Cubieboard2
PC Engines APU ---------------------------------BeagleBone Black
Debian 9/Sid---------------------------------------Virtual Machine

Select the right device for to download the install file and get live help from FreedomBox community by email and IRC chat.

DOWNLOAD | GET HELP | GET INVOLVED

**Comment by petterreinholdtsen** [comment]
[Philippe Baret]
> HOW TO START USING IT
>
> FreedomBox can be installed on open and cost-effectiv single board
> computers. Computers running Debian operating system (linux) and
> virtual machines are also supported. Here is the list of supported
> devices.
>
> A20 OLinuXino Lime2 ---------------------------Cubietruck
> A20 OLinuXino MICRO--------------------------Cubieboard2
> PC Engines APU ---------------------------------BeagleBone Black
> Debian 9/Sid---------------------------------------Virtual Machine

What does 'supported devices' mean here?  Should a different phrase be
used?  FreedomBox work on other devices besides those in this list.
Should those be listed too?

Seem like a bad idea to not mention all devices that can work with the
FreedomBox system, even if we do not recommend them because the need
binary firmware blobs.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by phylophyl** [comment]
Hello Petter, got it, this text won't apply because it does not fit to mray design

**Comment by mray** [comment]
Since we are talking about other mockups than the inital one i suggest #4 is a better place to continue for now.

**Comment by mray** [comment]
this issue can be closed now i think. we are past mockups.

**Comment by phylophyl** [comment]
what about having a quick launch mock up as well to have a clean short page ready in one week or two

then we can have the full site a bit later, this one requires some mid-term content efforts and some athoughts (install and how to will generate more questions than answers at the moment from my non tech guy experience, how to handle these questions if the site has a heavy traffic ? irc ? mails ? forum ?)

**Comment by mray** [comment]
If I get you right you want to propose a simple one-page design that is may be a fraction of what is planned but better than nothing?

I'd like to not go backwards from here and build a new, trimmed down version of the page.
I also don't want to mockup anymore when HTML and CSS are ready.

If we really want to first start working on a smaller version of the page i propose to still close this issue and create a new just for that.

**Comment by phylophyl** [comment]
sure, i'll let that open 2 or 3 days days for potential other reactions and close it
