### ISSUE TITLE
Team skills

### ISSUE THREAD

**Issue by phylophyl** [freedombox/freedombox.org#3]
People involved in freedombox.org landing page.

**Comment by phylophyl** [comment]
Philippe Baret
Journalist, online editing, seo, cms management, html, css, sass

**Comment by jvalleroy** [comment]
I think this can be closed (no TODOs)? Maybe add a section in https://wiki.debian.org/FreedomBox/TODO/TodoContent/LandingPage where people can add their names if they are interested in contributing.
