### ISSUE TITLE
Rephrase welcome text

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#34]
Here is what I have in mind:
FreedomBox is designed to be your _own_ inexpensive server at home. It runs free software and offers an increasing number of services ranging from a calendar or jabber server to a wiki or VPN. Our web interface allows you to easily install and configure your apps. Be your own host!

This is what it would look like:
![sptqi0il3m](https://cloud.githubusercontent.com/assets/164785/22331300/0b49c1f2-e3cb-11e6-93fa-6dc6a289c34e.png)

The choice of examples given can be changed. Calendar, jabber, wiki and VPN just seemed a good set to me.

the current text
> FreedomBox is your personal server. It couples free software with always-on, inexpensive and power-efficient hardware. Plug it into your home network, set it up and it will start hosting your address-book, calendar or blog right from your living room. With a few clicks in its web interface FreedomBox also runs a privacy defending VPN, ad-blockers and many more apps and services. A web interface acts as the central hub, offering one-click installs and simple configuration of apps and services.

 concerns I have over the current text:
- it is too long
- it makes assumptions about what it _can_ be and suggests it it does (uncertainty)
- it is arbitrarily specific (eg. calendar & living room)
- it is playing down technical issues (reachability from the outside net isn't a problem we solve), plugin in does not work

**Comment by jvalleroy** [comment]
Fixed in  #38.
