### ISSUE TITLE
Mockups are here, now what?

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#4]
Hi there, I worked on the mockups and uploaded them to [another repository (source+png)](https://github.com/mray/freedombox.org-mockup).

* **Texts are largely placeholder text!**
* As discussed the landing page now features 3 text segments that introduce possible features of the FB ("speech bubbles")
* Also every setup page now features a visually similiar segment right at the top that gives rationale on what the described feature does and why that matters.
* I cleaned up the spacing, everything is in its right place now
* Some minor style changes happened, mainly with cleanup and consistentcy in mind

From this point on we are good to go to start creating html versions of the page - unless mockup-relevant things need to change. Are there?

**Comment by mray** [comment]
For refererence the font is [Lato](https://www.google.com/fonts/specimen/Lato) and here is the [identiy guide](https://github.com/freedombox/Plinth/blob/master/static/themes/default/FreedomBox-Identity-Manual.pdf)

**Comment by SunilMohanAdapa** [comment]
@gnoutchd Please start working on creating HTML if you have not already done so.  I am available for assisting you or just discussing any technicalities.

**Comment by mray** [comment]
i've started on doing that now.

**Comment by mray** [comment]
I now have all the [mockups in css and html](https://github.com/mray/freedombox.org-mockup).
Currently there are quite a few different css files for clarity and one for each subpage. The CMS should reduce that amount. I'm also making use of css sprites there.

We can now start putting this into actual templates of any $CMS.
I did not put effort into making things responsive yet.
I'm sure my css isn't top quality, so re-ordering and general messing around with it is welcome.

So mockups are available in CSS + HTML - now what?

We need a CMS and we need the content.

**Comment by phylophyl** [comment]
sorry for this delay mray, i can put some effort on the content now

**Comment by phylophyl** [comment]
this look awesome to me, what would you suggest as a process to insert content in the pages and add "how to" pages ?

**Comment by mray** [comment]
I think now the "actual" work has to be done.

- We need to agree on a CMS

- A common format for guides (covering length, target hardware, target audience, ...) has to be defined somewhere.

- Then we need to agree on a few "how-to"s and create them (videos are essential i think), at least three I guess. I may need to create new icons for the respective "how-to"s

- We need to have a kick-ass introductory text to replace the lorem ipsum, also the longer text behind the "more about this project".

- We need to pave the way for people to easily get our "default" hardware and ideally other hardware; create links to shops or shopping sets on amazon (or better alternatives?).

- The links in the footer need to make more sense, I have no idea what needs to be present there.


Looking at that list i guess creating issues for each task makes working *and* talking about them easier.
