### ISSUE TITLE
Make FreedomBox reachable from the outside world

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#43]
### Problem
By default FreedomBox can't provide any features that require a connection from the "internet" back to your FreedomBox at home behind a router. The solutions we currently offer are not fit for a recommended default or an auto-set-up. Its drawbacks are:

#### 1. DynDNS / Pagekite

* DynDNS relies on a third party
 *can be expensive or unreliable - all services depend 100% on it*
 
* DynDNS is hard to set up automatically
*especially behind a router and with the variety of possible DynDNS services*

#### 2. Hidden Tor service

* put non-acceptable burden on *all* client side communication
 *needs extra tools installed and running on all devices -or- native application support*

* comes with a serious bandwidth limitation
*especially problematic for file synchronization, backups, music streaming, ...*

Blockchain based DNS solutions may offer an acceptable way to go?
[namecoin.org](https://namecoin.org/)? [Blockstack](https://blockstack.org)? ...

**Comment by mray** [comment]
this should have been an issue for plinth, not freedombox.org

**Comment by petterreinholdtsen** [comment]
[mray]
> ### Problem
> By default FreedomBox can't provide any features that require a
> connection from the "internet" back to your FreedomBox at home behind
> a router. The solutions we currently offer are not fit for a
> recommended default or an auto-set-up. Its drawbacks are:

Did you leave out pagekite on purpose?  It is the feature I use to make
my FreedomBox visible on the Internet.

--
Happy hacking
Petter Reinholdtsen

**Comment by mray** [comment]
Thanks for the note. Correct me if I'm wrong: it seems to have the identical downsides as DynDNS - only differing in technical details.

I'll add it to **1.** for now...

**Comment by petterreinholdtsen** [comment]
[mray]
> Thanks for the note. Correct me if I'm wrong: it seems to have the
> identical downsides as DynDNS - only differing in technical details.

Almost, but lack the problem with operating behind a router/firewall.

--
Happy hacking
Petter Reinholdtsen

**Comment by mray** [comment]
Oh right! Thinking about that difference reminds me of another issue: If I'm not mistaken Pagekite is limited in terms of the kinds of traffic it can tunnel. There is a limitation of bandwidth and possibly the kind of traffic that goes through, right? Like using bittorrent or something like that makes pagekite cringe?
It seemsto make sense to list it as a seperate solution attempt after all.

Lets better continue the issue over in the [plinth issue](https://github.com/freedombox/Plinth/issues/754) please : )
