### ISSUE TITLE
Upload slides template

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#46]
This should be on the [debian wiki](https://wiki.debian.org/FreedomBox/TalksAndPresentations) but I can't get an account there. Can anyone upload it to the wiki to close this issue?

## About the slides

I created a FreedomBox themed [reveal.js](http://lab.hakim.se/reveal-js) template.
This way you can easily create HTML slides and present them using FreedomBox logo, colors and fonts in any browser.

`demo.html` gives an overview what options you have in using reveal js.
`index.html` is the "empty" template waiting to be edited.

ZIP containing all necessary files:
[Freedombox reveal theme.zip](https://github.com/freedombox/freedombox.org/files/1104933/Freedombox.reveal.theme.zip)

**Comment by jvalleroy** [comment]
I uploaded the zip file and linked to it from that page. (Although I might suggest it better to fork https://github.com/hakimel/reveal.js/ and keep the changes in git.)
