### ISSUE TITLE
"Welcome" text

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#6]
We need a short (450 char) introduction text, that quickly explains what FB is. It should be very easily understandable and use no fancy terminology or too much "values" loaded langauge.

It would be great to give an idea how we are different than similiar projects and why.

**Comment by phylophyl** [comment]
Just to have a visual idea for 450 char : 

"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem"

**Comment by jvalleroy** [comment]
Here is one I started (289 chars), feel free to use/edit/ignore any part:

FreedomBox is your always-on personal server. It is Free Software (Debian) that runs on a variety of inexpensive and power-efficient hardware. FreedomBox hosts your blog, chat, voice calls, calendar, and bookmarks. It also provides services like ad blocking and VPN to defend your privacy.

**Comment by mray** [comment]
> FreedomBox is your always-on personal server.

I thin this works well, it is straight on and everybody can relate to that without special knowledge

> It is Free Software (Debian) that runs on a variety of inexpensive and power-efficient hardware.

I think referencing (Debian) is only valuable information for people who know what distros are, better avoid confusion and unknown terms.

>  FreedomBox hosts your blog, chat, voice calls, calendar, and bookmarks.

I think people might have problems imagining what "hosting chat" or "hosting voice calls" means.
*Chat* is something they just get from Signal, WhatsApp, Facebook, Threema, ... none of which we can offer to "host".
*Voice calls* typically are taken care of by the phone provider, even if we *could* provide SIP at some point, let's not suggest too confidently that we can host your telephony needs yet.

> It also provides services like ad blocking and VPN to defend your privacy.

I like that the more "special" services are listed at th end. There might be a hint that this isn't an exhaustive list of services.

**Comment by jvalleroy** [comment]
version 2 (492 characters):
FreedomBox is your always-on personal server. It is a free software stack that runs on a variety of inexpensive and power-efficient hardware. Plug a FreedomBox into your home network, and it will help
you get started self-hosting your blog, a chat server, conference calls, calendar, and more. FreedomBox also provides services like ad blocking and VPN to defend your privacy. A web interface acts as the central hub, offering one-click installs and simple configuration of apps and services.

**Comment by mray** [comment]
It is way better, still here are my thoughts:

> ... It is a free software stack...

I expect "software stack" to not be in the active vocabulary of our audience.

>  ...that runs on a variety of inexpensive and power-efficient hardware.
> Plug a FreedomBox...

This brings up a crucial point imho: we don't offer anything to plug. We need to be very clear in our wording about that. As long as we talk about the *distro* FreedomBox, at least.

I think a slightly more simplified and more experience oriented (less feature oriented) version might be an improvement.

#### My (rugged) take:

FreedomBox is your personal server. It is free software and runs great on always-on, inexpensive and power-efficient hardware. Plug it into your home network, set it up and it will start hosting your address-book, calendar or blog right from your living room.
With a few clicks in its web interface FreedomBox also runs a privacy defending VPN, ad-blockers and many more apps and services.

**Comment by Pk13055** [comment]
I would like to add the introduction but I cannot seem to find the source for the page.

**Comment by jvalleroy** [comment]
@Pk13055 For now, I think it can replace the text in this file:
https://github.com/freedombox/freedombox.org/blob/master/content/contents.lr

We also need to merge the design from https://github.com/mray/freedombox.org-mockup, but maybe that's a separate task.

**Comment by Pk13055** [comment]
@jvalleroy I think it's better to merge this design first then edit the text right? For now though, how's this:

> FreedomBox is your personal server. It couples free software with always-on, inexpensive and power-efficient hardware. Plug it into your home network, set it up and it will start hosting your address-book, calendar or blog right from your living room.
With a few clicks in its web interface FreedomBox also runs a privacy defending VPN, ad-blockers and many more apps and services.
 A web interface acts as the central hub, offering one-click installs and simple configuration of apps and services.

(If this seems okay, I can go ahead with the edit.)

**Comment by jvalleroy** [comment]
@Pk13055 I'd say go ahead. We can always change it later if needed.

**Comment by Pk13055** [comment]
@jvalleroy I've submitted a PR regarding this. Also, I've taken a look at @mray 's mock-up website and was wondering if I could pick it up?  As you said, we'd be replacing the current website with said mock-up sometime, so it makes more sense to make introduction/body changes to that template directly.

**Comment by jvalleroy** [comment]
Fixed in #15.

@Pk13055 I'll create a new issue to discuss merging the mock-up design.
